name: "require issue"
description: "Checks if issue exists"

inputs:
  host:
    description: 'Issue tracker hostname'
    required: true
  token:
    description: 'Issue tracker access token'
    required: true
  type:
    description: 'Issue tracker type'
    required: true
    default: jira
  type:
    description: 'Verifies pull request title'
    required: true
    default: true

runs:
  using: 'node12'
  main: 'index.js'
